server {
    listen 80;
    listen [::]:80;
    server_name hzlglobal.local www.hzlglobal.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name hzlglobal.local www.hzlglobal.local;

    root /home/pardus/Hosting/hzlglobal.local/out;
    index index.html;

    ssl_certificate /home/pardus/Hosting/Certificates/hzlglobal.local/hzlglobal.local.pem;
    ssl_certificate_key /home/pardus/Hosting/Certificates/hzlglobal.local/hzlglobal.local-key.pem;

    access_log /var/log/nginx/hzlglobal.local.access.log;
    error_log /var/log/nginx/hzlglobal.local.error.log;

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location ~* \.(css|js|mjs|png|jpg|jpeg|gif|ico|svg|webp|woff|woff2|ttf|eot)$ {
        expires max;
        access_log off;
        log_not_found off;
    }
}
